#!/usr/bin/env bash


red="\033[0;31m"
green="\033[0;32m"
yellow="\033[0;33m"
reset="\033[0m"
magenta="\033[0;35m"
cyan="\033[0;36m"
white="\033[0;37m"


test_file="$1"
source_file="$2"
output_file="$3"

echo -e "compiling ${magenta}$source_file ${white}into ${cyan}$output_file ${white}tested by ${yellow}$test_file"

gcc -Wall -Wextra -Werror -pedantic -std=gnu89 "$test_file" "$source_file" -o "$output_file"

if [ $? -eq 0 ]; then
    echo -e "${green}Compilation succeeded"

else
    echo -e "${red}Compilation failed"
fi
